# Generated by Django 3.2.4 on 2021-06-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('unique_id', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('min_timestamp', models.DateTimeField(verbose_name='Время начала хроники')),
                ('max_timestamp', models.DateTimeField(verbose_name='Время окончания хроники')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=6, verbose_name='Статус')),
                ('aircraft', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name': 'хроника',
                'verbose_name_plural': 'Хроники',
                'ordering': ('unique_id',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('unique_id', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(verbose_name='Время события хроники')),
                ('aircraft', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name': 'хроника',
                'verbose_name_plural': 'Хроники',
                'ordering': ('unique_id',),
            },
        ),
    ]
